project:
  type: website
  resources:
    - assets

website:
  title: "blog.cb"
  navbar:
    right:
      - icon: github
        href: https://github.com/chrisbrownlie
      - icon: linkedin
        href: https://www.linkedin.com/in/cnbrownlie/
      - text: "{{< iconify simple-icons:bluesky >}}"
        href: https://bsky.app/profile/bsky.chrisbrownlie.com
format:
  html:
    theme: zephyr
    css: styles.css



