name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quarto-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto --version

  render:
    needs: quarto-setup
    runs-on: ubuntu-latest
    steps:
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html # If set, it will be equivalent to `quarto render --to html`
        path: source-folder # By default, the current working dir is used i.e `quarto render .`

  build:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag christopherbrownlie/blog:$(date +%s)
