name: Build, Push and Deploy a Docker Image

on:
 push:
   branches: [main]

permissions:
  contents: read
  packages: write

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
 build-push-deploy-image:
   runs-on: ubuntu-20.04
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Log in to the Container registry
       uses: docker/login-action@v3.3.0
       with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push Docker image
       id: push
       uses: docker/build-push-action@v6.5.0
       with:
         context: .
         push: true
         tags: christopherbrownlie/blog:latest
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.DO_ACCESS_TOKEN }}
